version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf   
      - ./site/dist:/var/www/html
      - ./docs/site:/var/www/docs
    restart: always

  api:
    image: node:alpine
    container_name: rest
    volumes:
      - ./backend/api:/app
    ports:
      - "23450:8080"
    command: sh -c "cd /app && npm install && npm start"
    restart: always

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    env_file:
      - .env
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
