// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGRn1e8amdYhxHVav-DxK5n4751gDkdY',
    appId: '1:666477642597:web:945b242fbddf15eccdd78c',
    messagingSenderId: '666477642597',
    projectId: 'dwellow-ab144',
    authDomain: 'dwellow-ab144.firebaseapp.com',
    storageBucket: 'dwellow-ab144.appspot.com',
    measurementId: 'G-G76NN73D1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GCvDqRCqOhrIfkjM9ogs2tk6k41LJ74',
    appId: '1:666477642597:android:70969e2e0a534d0ccdd78c',
    messagingSenderId: '666477642597',
    projectId: 'dwellow-ab144',
    storageBucket: 'dwellow-ab144.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4KzCjDWFLUZyExJcXN-ZjbHPRQjdp4OE',
    appId: '1:666477642597:ios:c713d30f61ae8624cdd78c',
    messagingSenderId: '666477642597',
    projectId: 'dwellow-ab144',
    storageBucket: 'dwellow-ab144.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4KzCjDWFLUZyExJcXN-ZjbHPRQjdp4OE',
    appId: '1:666477642597:ios:c713d30f61ae8624cdd78c',
    messagingSenderId: '666477642597',
    projectId: 'dwellow-ab144',
    storageBucket: 'dwellow-ab144.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALGRn1e8amdYhxHVav-DxK5n4751gDkdY',
    appId: '1:666477642597:web:5bef2e3d579d6c29cdd78c',
    messagingSenderId: '666477642597',
    projectId: 'dwellow-ab144',
    authDomain: 'dwellow-ab144.firebaseapp.com',
    storageBucket: 'dwellow-ab144.appspot.com',
    measurementId: 'G-2688V03Y8G',
  );
}
