version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   
      - ../site/dist:/var/www/html
      - ../docs/site:/var/www/docs
    restart: always
