FROM mcr.microsoft.com/mssql/server:2019-latest

# Create a directory for your scripts
RUN mkdir -p /usr/config

# Copy the initialization and configuration scripts to the container
COPY ./dbscript.sql /app/
COPY ./configure-db.sh /usr/config/configure-db.sh
COPY ./entrypoint.sh /usr/config/entrypoint.sh

# Make the scripts executable
RUN chmod +x /usr/config/entrypoint.sh
RUN chmod +x /usr/config/configure-db.sh

# Set the entry point to your custom script
ENTRYPOINT ["/usr/config/entrypoint.sh"]
