version: '3'

services:
  databaser:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    env_file:
      - ../../.env
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
