on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Tailscale client
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        - name: Connect to Tailscale network
            run: |
              tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
              - name: Pull code with Git
                  run: |
                    git clone --single-branch --branch ${{ secrets.MAIN_BRANCH }} https://github.com/gabeele/dwellow.git ${{ secrets.WORK_DIR }}
                    cd ${{ secrets.WORK_DIR }}
                    git pull
                    docker-compose restart api nginx web
                    exit

